import { TeaCategory, TeaListItem } from './types';

// 根据用户提供的目录图片整理的完整清单
export const TEA_CATALOG: TeaListItem[] = [
  // --- 号级茶 (Antique) ---
  { id: 'song-pin', name: '宋聘号·红标', category: TeaCategory.ANTIQUE, page: 12 },
  { id: 'song-pin-blue', name: '宋聘号·蓝标', category: TeaCategory.ANTIQUE, page: 13 },
  { id: 'yang-pin', name: '杨聘号', category: TeaCategory.ANTIQUE, page: 14 },
  { id: 'chen-yun', name: '陈云号·白纸黑标', category: TeaCategory.ANTIQUE, page: 15 },
  { id: 'pu-qing', name: '普庆号', category: TeaCategory.ANTIQUE, page: 15 },
  { id: 'che-shun', name: '车顺号', category: TeaCategory.ANTIQUE, page: 16 },
  { id: 'fu-yuan-chang', name: '福元昌号·蓝票', category: TeaCategory.ANTIQUE, page: 16 }, // 原ID保留，修正名称
  { id: 'fu-yuan-chang-purple', name: '福元昌号·紫票', category: TeaCategory.ANTIQUE, page: 17 },
  { id: 'tong-qing', name: '同庆号·龙马商标', category: TeaCategory.ANTIQUE, page: 18 },
  { id: 'tong-qing-lion', name: '同庆号·双狮旗图', category: TeaCategory.ANTIQUE, page: 19 },
  { id: 'tong-xing-xiang', name: '同兴号·向质卿', category: TeaCategory.ANTIQUE, page: 20 },
  { id: 'tong-xing-sheng', name: '同兴号·向绳武', category: TeaCategory.ANTIQUE, page: 21 },
  { id: 'jing-chang', name: '敬昌号', category: TeaCategory.ANTIQUE, page: 22 },
  { id: 'jiang-cheng', name: '江城号', category: TeaCategory.ANTIQUE, page: 23 },
  { id: 'ding-xing-blue', name: '鼎兴茶庄·蓝票', category: TeaCategory.ANTIQUE, page: 24 },
  { id: 'ding-xing-red', name: '鼎兴茶庄·红票', category: TeaCategory.ANTIQUE, page: 24 },
  
  // --- 印级茶 (Print) ---
  { id: 'red-mark-nopaper', name: '无纸红印圆茶', category: TeaCategory.PRINT, page: 20 },
  { id: 'red-mark-a', name: '蓝印圆茶 (甲乙级)', category: TeaCategory.PRINT, page: 21 },
  { id: 'green-mark-big', name: '大字绿印茶圆', category: TeaCategory.PRINT, page: 22 },
  { id: 'iron-cake-blue', name: '蓝印铁饼圆茶', category: TeaCategory.PRINT, page: 23 },
  { id: 'yellow-mark', name: '八中黄印', category: TeaCategory.PRINT, page: 24 },
  { id: 'yellow-mark-recipe', name: '黄印认真配方', category: TeaCategory.PRINT, page: 25 },
  { id: 'seven-yellow-small', name: '七子小黄印', category: TeaCategory.PRINT, page: 26 },
  { id: 'apple-green', name: '七子苹果绿黄印', category: TeaCategory.PRINT, page: 27 },

  // --- 七子饼 (Seven Sons) ---
  { id: '7572-big', name: '7572 大口中', category: TeaCategory.SEVEN_SONS, page: 28 },
  { id: 'blue-mark-7', name: '七子大蓝印', category: TeaCategory.SEVEN_SONS, page: 29 },
  { id: 'iron-cake-7', name: '昆明七子铁饼', category: TeaCategory.SEVEN_SONS, page: 30 },
  { id: 'xiaguan-simplified', name: '下关简体字', category: TeaCategory.SEVEN_SONS, page: 31 },
  { id: '73-thick', name: '七三厚砖', category: TeaCategory.SEVEN_SONS, page: 32 },
  { id: '79-jinggu', name: '七九景谷文革砖', category: TeaCategory.SEVEN_SONS, page: 33 },
  { id: 'big-leaf-green', name: '特级大叶青饼', category: TeaCategory.SEVEN_SONS, page: 34 },
  { id: '8582-paper', name: '厚纸 8582 青饼', category: TeaCategory.SEVEN_SONS, page: 35 },
  { id: 'snow-mark', name: '雪印青饼', category: TeaCategory.SEVEN_SONS, page: 36 },
  { id: '73-green', name: '七三青饼 (小绿印)', category: TeaCategory.SEVEN_SONS, page: 37 },
  { id: '7542-thick', name: '厚纸 7542 青饼', category: TeaCategory.SEVEN_SONS, page: 38 },
  { id: '7532-thick', name: '厚纸 7532 青饼', category: TeaCategory.SEVEN_SONS, page: 39 },
  { id: '8582-thin', name: '薄纸 8582 青饼', category: TeaCategory.SEVEN_SONS, page: 40 },
  { id: '88-qing', name: '88青饼 (7542)', category: TeaCategory.SEVEN_SONS, page: 41 },
  { id: '8653-traditional', name: '下关繁体字 8653', category: TeaCategory.SEVEN_SONS, page: 42 },
  { id: '92-fangzhuan', name: '九二方砖', category: TeaCategory.SEVEN_SONS, page: 43 },
  { id: '96-purple', name: '96 紫大益青饼', category: TeaCategory.SEVEN_SONS, page: 45 },
  { id: '96-zhenchun', name: '96 真淳号', category: TeaCategory.SEVEN_SONS, page: 46 },
  { id: '97-water-blue', name: '1997 水蓝印青饼', category: TeaCategory.SEVEN_SONS, page: 47 },
  { id: '98-red-dayi', name: '98 红大益青饼', category: TeaCategory.SEVEN_SONS, page: 48 },
  { id: '99-green-tree', name: '99 绿大树', category: TeaCategory.SEVEN_SONS, page: 50 },
  
  // --- 班章 / 孔雀时代 (Banzhang/Peacock) ---
  // 2000-2002
  { id: '2000-rubber-band', name: '橡筋饼 (班章野生茶)', category: TeaCategory.BANZHANG_PEACOCK, page: 51 },
  { id: '2000-treasure', name: '2000年 班章珍藏青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 52 },
  { id: '2000-grade1', name: '2000年 班章一级青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 53 },
  { id: '2000-cabbage-200g', name: '2000年 班章小白菜 200克', category: TeaCategory.BANZHANG_PEACOCK, page: 55 },
  { id: '2002-star-king', name: '2002年 201 班章茶王青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 60 },
  { id: '2002-eco-big', name: '2002年 班章生态大叶青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 61 },
  { id: '2002-201-treasure', name: '2002年 201 班章珍藏精品', category: TeaCategory.BANZHANG_PEACOCK, page: 62 },
  { id: '2002-special', name: '2002年 201 班章特制精品', category: TeaCategory.BANZHANG_PEACOCK, page: 63 },
  { id: '2002-no2', name: '2002年 班章二号青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 64 },
  
  // 2003
  { id: '2003-6star-peacock', name: '2003年 班章六星孔雀', category: TeaCategory.BANZHANG_PEACOCK, page: 67 },
  { id: '2003-5star-peacock', name: '2003年 班章五星孔雀', category: TeaCategory.BANZHANG_PEACOCK, page: 68 },
  { id: '2003-4star-peacock', name: '2003年 班章四星孔雀', category: TeaCategory.BANZHANG_PEACOCK, page: 69 },
  { id: '2003-peacock-357', name: '2003年 孔雀青饼 357克', category: TeaCategory.BANZHANG_PEACOCK, page: 70 },
  { id: '2003-arbor-tuo', name: '2003年 班章乔木生态沱', category: TeaCategory.BANZHANG_PEACOCK, page: 71 },
  { id: '2003-4mark-banzhang', name: '2003年 四印班章青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 72 },
  { id: '2003-2mark-banzhang', name: '2003年 班章二号青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 73 },
  { id: '2003-4star-banzhang', name: '2003年 班章四星青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 74 },
  { id: '2003-3star-banzhang', name: '2003年 班章三星青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 75 },
  { id: '2003-301-green-eco', name: '2003年 301 绿色生态青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 77 },
  { id: '2003-301-spring', name: '2003年 301 早春乔木青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 80 },
  { id: '2003-eco-tuo', name: '2003年 班章生态孔雀青沱', category: TeaCategory.BANZHANG_PEACOCK, page: 81 },
  { id: '2003-peacock-tuo', name: '2003年 孔雀青沱', category: TeaCategory.BANZHANG_PEACOCK, page: 82 },
  { id: '2003-eco-brick', name: '2003年 班章生态青砖', category: TeaCategory.BANZHANG_PEACOCK, page: 83 },
  { id: '2003-301-golden', name: '2003年 301 金大益青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 84 },
  { id: '2003-301-silver', name: '2003年 301 银大益青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 85 },
  { id: '2003-302-silver', name: '2003年 302 银大益青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 86 },
  { id: '2003-nannuo-wild', name: '2003年 301 南糯野生饼茶', category: TeaCategory.BANZHANG_PEACOCK, page: 87 },
  { id: '2003-101-8582', name: '2003年 101 8582', category: TeaCategory.BANZHANG_PEACOCK, page: 89 },

  // 2004
  { id: '2004-treasure-tuo', name: '2004年 班章珍藏青沱', category: TeaCategory.BANZHANG_PEACOCK, page: 90 },
  { id: '2004-king-500g', name: '2004年 班章茶王青饼 500克', category: TeaCategory.BANZHANG_PEACOCK, page: 91 },
  { id: '2004-treasure-cake', name: '2004年 班章珍藏青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 92 },
  { id: '2004-boutique', name: '2004年 班章精品青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 93 },
  { id: '2004-eco', name: '2004年 班章生态茶', category: TeaCategory.BANZHANG_PEACOCK, page: 94 },
  { id: '2004-peacock-gong', name: '2004年 孔雀班章贡青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 95 },
  { id: '2004-401-peacock', name: '2004年 401 孔雀班章饼', category: TeaCategory.BANZHANG_PEACOCK, page: 96 },
  { id: '2004-yellow-dayi', name: '2004年 黄大益班章野生茶', category: TeaCategory.BANZHANG_PEACOCK, page: 97 },
  { id: '2004-shen-ao', name: '2004年 申奥饼', category: TeaCategory.BANZHANG_PEACOCK, page: 98 },
  { id: '2004-7542', name: '2004年 7542', category: TeaCategory.BANZHANG_PEACOCK, page: 100 },

  // 2005
  { id: '2005-501-peacock', name: '2005年 501 勐海孔雀饼茶', category: TeaCategory.BANZHANG_PEACOCK, page: 101 },
  { id: '2005-501-bulang', name: '2005年 501 布朗孔雀青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 102 },
  { id: '2005-501-mengsong', name: '2005年 501 勐宋孔雀饼茶', category: TeaCategory.BANZHANG_PEACOCK, page: 103 },
  { id: '2005-501-wujin', name: '2005年 501 乌金号', category: TeaCategory.BANZHANG_PEACOCK, page: 103 },
  { id: '2005-gold-rhyme-yellow', name: '2005年 501 金色韵像(黄)', category: TeaCategory.BANZHANG_PEACOCK, page: 104 },
  { id: '2005-gold-rhyme-green', name: '2005年 501 金色韵像(绿)', category: TeaCategory.BANZHANG_PEACOCK, page: 105 },
  { id: '2005-white-cloth', name: '2005年 501 7542 白布条', category: TeaCategory.BANZHANG_PEACOCK, page: 106 },
  { id: '2005-7742', name: '2005年 501 7742(越陈越香)', category: TeaCategory.BANZHANG_PEACOCK, page: 107 },

  // 2006
  { id: '2006-peacock-cake', name: '2006年 601 勐海孔雀饼茶', category: TeaCategory.BANZHANG_PEACOCK, page: 109 },
  { id: '2006-bulang-peacock', name: '2006年 601 布朗孔雀饼茶', category: TeaCategory.BANZHANG_PEACOCK, page: 110 },
  { id: '2006-song-peacock', name: '2006年 601 勐宋孔雀饼茶', category: TeaCategory.BANZHANG_PEACOCK, page: 111 },
  { id: '2006-laobanzhang', name: '2006年 州政府老班章', category: TeaCategory.BANZHANG_PEACOCK, page: 112 },
  { id: '2006-organic-bz', name: '2006年 601 班章有机青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 113 },
  { id: '2006-manmai', name: '2006年 601 曼迈兑青饼', category: TeaCategory.BANZHANG_PEACOCK, page: 114 },
  { id: '2006-yanyun', name: '2006年 601 岩韵', category: TeaCategory.BANZHANG_PEACOCK, page: 115 },
  { id: '2006-high-mountain', name: '2006年 601 高山韵象', category: TeaCategory.BANZHANG_PEACOCK, page: 116 },
];